#cloud-config

# Set the hostname and FQDN
fqdn: docs-cd
manage_etc_hosts: true

# Set the timezone to UTC (strongly recommended)
timezone: UTC

# Set the locale
locale: en_US.UTF-8

# Run package update and upgrade on first boot
package_upgrade: true

# Install packages
packages:
  - git
  - apache2
  - python-virtualenv
  - python-pip
  - python-dev
  - unattended-upgrades

# Run commands (in order, output displayed on the console)
runcmd:
  # Enable unattended upgrades
  - echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
  - dpkg-reconfigure -fnoninteractive unattended-upgrades
  # Disable apache's default site
  - rm -rf /etc/apache2/sites-enabled/000-default.conf /etc/apache2/sites-available/000-default.conf /var/www/html
  # Clone docs-cd
  - git clone https://github.com/catalyst/docs-cd.git /home/ubuntu/docs-cd
  - chown ubuntu.ubuntu /home/ubuntu/docs-cd
  # Create a cron job that checks for updates compiles documentation every hour.
  - echo "0 * * * * /home/ubuntu/docs-cd/docs-cd.py -c /home/ubuntu/docs-cd/config.yaml -l /home/ubuntu/docs-cd/docs-cd.log" > /var/spool/cron/crontabs/ubuntu
  - chmod 600 /var/spool/cron/crontabs/ubuntu
  - chown ubuntu.crontab /var/spool/cron/crontabs/ubuntu
  # Create a cron job that updates apache's configuration every minute, if there
  # is a need to change it.
  - echo "* * * * * /home/ubuntu/docs-cd/docs-publish.py -c /home/ubuntu/docs-cd/config.yaml -t /home/ubuntu/docs-cd/vhost.cfg -l /home/ubuntu/docs-cd/docs-publish.log" > /var/spool/cron/crontabs/root
  - chmod 600 /var/spool/cron/crontabs/root
  - chown root.crontab /var/spool/cron/crontabs/root

# Reboot when finished
power_state:
  mode: reboot
  message: Rebooting to apply new settings

# Log all cloud-init process output (info & errors) to a logfile
output: {all: ">> /var/log/cloud-init-output.log"}
