---

# ============================================================================
# Attributes for configuring docs-cd instance
# ============================================================================

# if set to true this will add the instance name and IP addess to the user's
# local machine /etc/hosts file.
# This option requires -K to be passed to the ansible-playbook command to
# prompt for sudo password
set_local_host_entry: false

timezone: UTC
# the user account that will manage the docs-cd instance
docs_user: ubuntu
# the install directory, assumed to be relative to docs_user directory
docs_install_dir: docs-cd
# docs-cd full installation path
docs_dir: "/home/{{ docs_user }}/{{ docs_install_dir }}"

crontab_users:
  - ubuntu
  - root
crontab_entry_docs_user:
  - "0 * * * * {{ docs_dir }}/docs-cd.py -c {{ docs_dir }}/config.yaml -l {{ docs_dir }}/docs-cd.log"
crontab_entry_root_user:
  - "* * * * * {{ docs_dir }}/docs-publish.py -c {{ docs_dir }}/config.yaml -t {{ docs_dir }}/templates/vhost_template.cfg -l {{ docs_dir }}/docs-publish.log"
