---
# OpenStack authentication variables (not required if RC sourced)
#os_auth_url: https://api.cloud.catalyst.net.nz:5000/v2.0
#os_region: nz-por-1
#os_az: nz-por-1a
#os_project_name: projectname
#os_username: username
#os_password: password

# Attributes used for launching the compute instance (required)
image: ubuntu-16.04-x86_64
private_network_name: private-net
keypair_name: keypair
instance_name: docs-cd
flavor: c1.c1r1
security_group_name: docs-cd
user_data: cloud-init.yaml
expose_ssh_to: 0.0.0.0/0
